#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <namespace> <resource-type>"
    exit 1

fi

NAMESPACE=$1
RESOURCE_TYPE=$2

kubectl get $RESOURCE_TYPE -n $NAMESPACE --no-headers | while read -r NAME CPU MEMORY REST
do 

    echo "$RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY"

done


